### ISSUE TITLE
RUN ERROR 

### ISSUE THREAD

**Issue by pretech86** [whitehauler/lemon-ate#1]
WHEN I TRY sh php i get 

[-] Please make sure you are connected to the Internet :(

**Comment by whitehauler** [comment]
just do
**chmod +x Install**
then run **sh ./Install**

**Comment by whitehauler** [comment]
its just for checking internet connection
don't worry about that
just do
1.git clone https://github.com/whitehauler/lemon-ate.git
2.then cd lemon-ate
3.chmod +x Install
4.then run sh ./Install
